### ISSUE TITLE
Support a weighted analysis with acceptance correction in binned polarization cubes and friends

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ixpeobssim#573]
This is spin-off of issue #565, from which I copy here the summary tables.

|  | **1: w/o W, w/o AC** | **2: w/o W, w/ AC** | **3: w/ W, w/o AC** | **4: w/ W, w/ AC** |
| --- | --- | --- | --- | --- |
| E\_MEAN | 2.929 keV | **3.696 keV** | 3.267 keV | 4.318 keV |
| PD | 0.2993 \(-12.1 sigma\) | **0.3760 \(\+0.9 sigma\)** | 0.3324 \(-7.5 sigma\) | 0.4347 \(\+8.0 sigma\) |
| PD\_ERR | 0.0058 | 0.0068 | 0.0050 | 0.0081 |
| MDP | **0.0175** | 0.0207 | **0.0154** | 0.0248 |

‌

|  | **1: w/o W, polconst** | **2: w/o W, pollin** | **3: w/ W, polconst** | **4: w/ W, pollin** |
| --- | --- | --- | --- | --- |
| Chisquare | 1725.74 / 1337 | 1253.04 / 1335 | 1721.49 / 1337 | 1242.91 / 1335 |
| PD | 0.3728 \+/- 0.0057 | - | 0.3690 \+/- 0.0052 | - |
| PD intercept | - | 0.094 \+/- 0.014 | - | 0.1121 \+/- 0.0052 |
| PD slope | - | 0.111 \+/- 0.013 | - | 0.1041 \+/- 0.0048 |

‌

I had a lot of back and forth with Carmelo on this, but the provisional conclusions are:

* the specifics we used to define the weighted response functions match the strategy we use to create PHA1\* files to be fed into XSPEC, and there’s no issue there;
* the polarization cubes and friends now allow to disengage the acceptance corrections, and this provides the MDP values that one would naively expect in both the un-weighted and weighted cases---the latter match the output of the WebPIMMS modulo slight difference in the response functions used;
* disengaging the acceptance correction in polarization cubes introduces potentially large biases when the polarization degrees changes with energy;
* the un-weighted polarization analysis with acceptance correction works as advertised and should be the baseline, at the moment;
* the output of the weighted polarization analysis with acceptance correction is not currently yielding what one would expect and should not be used.

About the last bullet, this is essentially due to the fact that we used the effective number of events \(as opposed to the weighted counts\) in the response functions, and it is not trivial to recast an unbinned analysis in that fashion.

Moving on we shall keep track of the progress in this issue.

Original url: https://bitbucket.org/ixpesw/ixpeobssim/issues/573
Created on 2022-02-17T12:57:47.628248+00:00

**Comment by lucabaldini** [comment]
Working on this one... 
https://github.com/lucabaldini/ixpeobssim/pull/700

**Comment by lucabaldini** [comment]
Ok, I have run a first end-to-end test, where I created a set of photon lists with a simple point source with a power-law energy spectrum and a polarization degree increasing with energy

```
xpphotonlist.py --config ixpeobssim/config/toy_pollin.py --dithering False --duration 10000 --saa False --occult False
```

run the actual Geant 4 simulations feeding the photon lists into ixpesim

```
ixpesim --src-photon-list ~/ixpeobssimdata/toy_pollin_du1_photon_list.fits --output-file ~/ixpeobssimdata/toy_pollin_du1_ixpesim.fits -n 10000000 --dme-pressure 645
ixpesim --src-photon-list ~/ixpeobssimdata/toy_pollin_du2_photon_list.fits --output-file ~/ixpeobssimdata/toy_pollin_du2_ixpesim.fits -n 10000000 --dme-pressure 631
ixpesim --src-photon-list ~/ixpeobssimdata/toy_pollin_du3_photon_list.fits --output-file ~/ixpeobssimdata/toy_pollin_du3_ixpesim.fits -n 10000000 --dme-pressure 638
```

reconstruct the FITS files and format them to be fed back into ixpeobssim.

**Comment by lucabaldini** [comment]
Shipped in 30.3.0

**Comment by fabiomuleri2** [comment]
@lucabaldini I'm not sure that it is not an hiccup of low statistics or spectral shape, but it seems that background-subtracted MDP may *worsen* with weights at low energy.

Step to reproduce with attached [pcubes](https://file.sic.rm.cnr.it/index.php/s/EiFfqdcj0O7nW91) (which refers to the latest magnetar, for which we have a source not much brighter than the background):
`from ixpeobssim.binning.polarization import xBinnedPolarizationCube`
```
def pcube(det, reg, w):
    file=f'ixpe02002899_det{det}_evt2_v02_rej_csol_bar_{reg}_{w}_PC_EBINS.fits'
    return xBinnedPolarizationCube.from_file_list([file])
```

Prints the MDP_99 in the first energy bin (2.0-3.5 keV) for the source alone:
```
for _d in [1,2,3]:
    _uwgt = pcube(det=_d, reg='src', w='uwgt').MDP_99[0]
    _wgt = pcube(det=_d, reg='src', w='wgt').MDP_99[0]
    print('******************************************************')
    print(f'*** det{_d}_src: {_uwgt:.4f} vs {_wgt:.4f}')
    print('******************************************************')
```
> *** det1_src: uwgt 0.4565 vs wgt 0.4359
> *** det2_src: uwgt 0.4759 vs wgt 0.4519
> *** det3_src: uwgt 0.4915 vs wgt 0.4728

Then, the MDP improves.

If we now subtract the background:
```
area_scale = 0.000314159265358979/0.01248783079801943
for _d in [1,2,3]:
    _uwgt_src = pcube(det=_d, reg='src', w='uwgt')
    _uwgt_bkg = pcube(det=_d, reg='bkg', w='uwgt')
    _uwgt_bkg *= area_scale
    _uwgt_src -= _uwgt_bkg
    
    _wgt_src = pcube(det=_d, reg='src', w='wgt')
    _wgt_bkg = pcube(det=_d, reg='bkg', w='wgt')
    _wgt_bkg *= area_scale
    _wgt_src -= _wgt_bkg
    
    print(f'*** det{_d}_src: {_uwgt_src.MDP_99[0]:.4f} vs {_wgt_src.MDP_99[0]:.4f}')
```
this prints:

> *** det1_src: 0.5455 vs 0.5519
> *** det2_src: 0.5840 vs 0.5758
> *** det3_src: 0.6111 vs 0.6171

and then only det2 improves. 

Cyg X-3 (which is much brighter than the background) works as one would naively expect (pcube  [here](https://file.sic.rm.cnr.it/index.php/s/UNx8zDpKgPAwQs8) ).

**Comment by lucabaldini** [comment]
Ciao Fabio, 
since this is an old issue now closed, I moved the discussion at
https://github.com/lucabaldini/ixpeobssim/issues/703
