### ISSUE TITLE
Connect the ixpeobssim public repo to some sensible CI

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ixpeobssim#624]
In the old days we used CircleCI, but maybe this is something we can do internally to github?

**Comment by ndilalla** [comment]
Working on this on the ``setup_github_actions`` branch. You can see the first triggered actions here: https://github.com/lucabaldini/ixpeobssim/actions

**Comment by lucabaldini** [comment]
Shipped in 29.2.0
