### ISSUE TITLE
Make ixpeobssim pip-installable.

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ixpeobssim#625]

**Comment by lucabaldini** [comment]
@ndilalla I merged the pull request with the refactoring necessary for the setup.py to work. This is all yours!

**Comment by ndilalla** [comment]
Ok, I created the draft pull request #642. The tests are currently failing for issue #631. Once we merge pull request #641, we should good to go

**Comment by lucabaldini** [comment]
Shipped in 29.2.0

**Comment by lucabaldini** [comment]
Shipped in 29.2.0
