### ISSUE TITLE
unit test failing

### ISSUE THREAD

**Issue by albertomanfreda** [lucabaldini/ixpeobssim#629]
ERROR: test_old_1708 (test_magnetar_table_models.TestMagnetarTableModels)
Comparison with the old 1708 model. Note that the two don't need to be
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alberto/xpe/ixpeobssim/tests/test_magnetar_table_models.py", line 62, in test_old_1708
    phase, energy, flux, pol_deg, pol_ang = parse_legacy_data(file_path, False, 0.53, 9.5)
  File "/home/alberto/xpe/ixpeobssim/ixpeobssim/srcmodel/magnetar.py", line 78, in parse_legacy_data
    with open(file_path, 'r') as input_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/alberto/xpe/ixpeobssim/ixpeobssim/config/ascii/axp_1rxs_j1708_phase_energy_1708-90-60-05-034.dat'

The file seems not to be present in the repo. This is likely a deprecated unit test.

**Comment by lucabaldini** [comment]
Branch: https://github.com/lucabaldini/ixpeobssim/tree/restore_missing_files

**Comment by lucabaldini** [comment]
Shipped in 29.1.1
