### ISSUE TITLE
Add a single event display

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ixpeobssim#639]
We should have a single event display operating on level-1 files---this should be relatively straightforward using what we have in gpdswpy.

And this would be the first step for the glorious animation that Brian et al. asked for the winter AAS.

**Comment by albertomanfreda** [comment]
Do you want to bring the event display in ixpeobssim?

**Comment by lucabaldini** [comment]
> Do you want to bring the event display in ixpeobssim?

The pure-python one, of course---not the C++, Qt-based one, if that's what you had in mind :-)

**Comment by lucabaldini** [comment]
I have a first rough cut at this on the event_display branch. It seems to work fine with Level-1 data, and we need to cleanup things a little bit.

https://github.com/lucabaldini/ixpeobssim/commit/d9e824b62104cfeb0e21897fdebae6fdeb9d6ab2

**Comment by lucabaldini** [comment]
Shipped in 29.4.0
