### ISSUE TITLE
setup_gca() grids option unexpected behavior

### ISSUE THREAD

**Issue by albertomanfreda** [lucabaldini/ixpeobssim#647]
ixpeobssim.utils.matplotlib_.setup_gca() is using

`plt.grid(which='both')`

to turn on the grids if grids == True. However, if setup.gca() is calling multiple times on the same plot, this actually turns the grids on e off each time it is called. I suggest switching to 

`plt.grid(True, which='both')`

**Comment by lucabaldini** [comment]
Pull request merged into the main branch

**Comment by lucabaldini** [comment]
Shipped in 29.3.0
