### ISSUE TITLE
Add more flexibility to the background template generation

### ISSUE THREAD

**Issue by s-silvestri** [lucabaldini/ixpeobssim#663]
Hi,
I've encountered some difficulties in simulating the residual background after a rejection cut and i think that we could rethink this in a more flexible way.
There is an issue with the current value of the FIDUCIAL_HALF_SIZE stored in ixpeobssim.instrument.gpd, at least when it's being used to simulate the instrumental background. The current value is of 7.35 but most observations have a fiducial cut of 6.8, and some older ones have a larger fiducial area.

The result is that when one tries to simulate a background from a template it systematically overshoots the real background at the border of the FoV.
The way it works now is that whenever an xTemplateInstrumentalBackground object is created the GPD fiducial area is taken from ixpeobssim.instrument.gpd, and that value is 7.35. We might want to make this slightly less hardcoded, although the default behaviour is probably ok.

Also, Some sources have a background field which is not entirely flat in detector coordinates, showing a trend that is **almost** always increasing at the border of the detector. It might be a good idea to implement a keyword to have the background scaled with the radius. I attach a couple of figures of extreme cases which show how much the radial profile of the background can differ from one source (and quite often one du) to another, showing also how in two different sources we have a different fiducial cut

![Radial_plot_3c273_du3](https://user-images.githubusercontent.com/69473621/201969262-a6021d88-8804-4393-b641-251050b905ba.png)
![Radial_plot_s05_du3](https://user-images.githubusercontent.com/69473621/201969269-8b01d413-04fc-4617-957f-f4f56f136ca0.png)

**Comment by lucabaldini** [comment]
Ok, I think most of the necessary stuff is in place in this pull request: https://github.com/lucabaldini/ixpeobssim/pull/666

**Comment by lucabaldini** [comment]
Shipped in 29.5.0
