### ISSUE TITLE
IRF generation support broken

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ixpeobssim#678]
In the process of adding support for the photon list mechanism we have largely broken the code path supporting the creation of the auxiliary files for the generation of response files (which we have not exercised in a couple of years, now).

More specifically, the `xpsimfmt` application, which is the first step in the process, is now assuming to get all the information in the input reconstructed files that is only there when using photon lists: DU ID, SC_DATA and alike.

While the photon list mechanism is probably the prime use for xpsimfmt, we should restore support for formatting reconstructed files for the IRF generation.

**Comment by lucabaldini** [comment]
First relevant commit: https://github.com/lucabaldini/ixpeobssim/commit/06fb84c85c0c090f51936e349ede8e514e091cf2

**Comment by albertomanfreda** [comment]
The commit seems ok to me. I have tested the change on a recon file produced with the end-to-end workflow and it works well. What other kind of files is ixpesimfmt supposed to work with? I actually never knew there was a different one. Is it something I can test?

**Comment by s-silvestri** [comment]
I gave it a quick look this morning and I had the same impression of
Alberto.
You can go ahead.

Il ven 16 dic 2022, 14:07 Luca Baldini ***@***.***> ha
scritto:

**Comment by lucabaldini** [comment]
Shipped in 29.1.0
