### ISSUE TITLE
Incorrect exposure in XSPEC readable spectra for a time-filtered IXPE observation

### ISSUE THREAD

**Issue by yashbhargava1992** [lucabaldini/ixpeobssim#698]
Hi,

I was trying to extract the spectrum (I,Q,U) for a short part of an observation. To get the short segment of the observation, I filter events using `ixpeobssim.core.pipeline.xpselect` with `tmin` and `tmax` keywords. From the filtered event file, I extracted the spectrum and lightcurve using the respective binning routines. 
 I noticed that the exposure of the spectrum is identical to the full duration observation and thus the estimates count rates (and thus flux) are reduced by factor of intended exposure/full exposure. The lightcurve indicates the same thing. The filtering was done correctly but the all the removed points were assigned a count rate of zero. I think the reduced count rate in the spectra is due to inclusion of zeros (and thus the unneeded exposure). 

Regards
Yash Bhargava

**Comment by lucabaldini** [comment]
Hi Yash, thanks for reporting this.

This is a know "issue", stemming from the fact that updating the exposure taking properly into account the deadtime is impossible just using level-2 data---you really need to go back to unfiltered level-1 data and sum the livetime column to do this properly.

I realize we could make up an approximate correction based on the information in level-2 data, but I am reluctant to do something that might spectacularly fail under specific condition.
