### ISSUE TITLE
PCUBE overestimation of polarization with gray filter below 3 KeV

### ISSUE THREAD

**Issue by fabiolamonaca** [lucabaldini/ixpeobssim#714]
A discrepancy in the energy-resolved analysis of Sco X-1 appears below 3 keV: PCUBE seems to overestimate polarization with respect to XSPEC in the 2-3 keV energy bin. The overestimation disappears if the acceptcorr is not enabled (plot attached).

![PD_PA_vs_energy_1keV_acceptcorr](https://github.com/lucabaldini/ixpeobssim/assets/103111154/0936d1fa-ce86-4f7d-b7d6-b3eed9b31933)

**Comment by dovciak** [comment]
I am attaching similar graph for Swift J1727.8-1613. Weighted PCUBE algorithm with gray filter with and without acceptcorr is compared to "plot polfrac" and "plot polangle" in XSPEC using weighted PHA1 algorithm with gray filter. It seems that acceptcorr="False" compares better...
![SwiftJ1727-6bins-comp-PD-PA](https://github.com/lucabaldini/ixpeobssim/assets/145338121/a18372a9-4f0a-4d83-a197-7c7c0c5582ea)

**Comment by lucabaldini** [comment]
As I pointed out in a couple of threads, the fact that disengaging the acceptance correction gives an answer that it closer to XSPEC must be purely coincidental. Without acceptance correction, the measured polarization is an instrument-dependent quantity that can be taken, at the very best, to be a proxy of the source polarization at the average recorded energy (which is also instrument-dependent). If the question you are asking is "what is the average source polarization in a given energy band" (which I think is what we are typically doing), then the acceptance correction *must* be applied.

We know that the model-independent analysis comes with limitations (most notably, the energy dispersion is neglected), and when this becomes measurable we should just correct for it. (One simple way is to run a representative simulation and look at the difference between a PCUBE in measured energy and the corresponding in true energy.)

This very old issue https://github.com/lucabaldini/ixpeobssim/issues/363 is relevant for this discussion.

**Comment by dovciak** [comment]
So the question is which is the closest to the real PD and PA "before detector"... The unweighted or weighted PCUBE with acceptcorr='True' or polfrac and polangle from weighted or unweighted PHA1? I.e. which should we present in the papers?

**Comment by lucabaldini** [comment]
Good question. I don't think we have any reason to doubt XSPEC, so that would be my first benchmark. (Weighted or unweighted should not make a big difference, the two should be consistent between each other, with the former providing a slightly smaller error bar.)

I am afraid the only quantitative way to understand what *exactly* is biting us with the model-independent analysis, is via a simulation of a large ensemble of realizations, and not just change settings with real data. If and when we understand that, as I said, I can imagine many ways to apply a sensible correction.

By the way, I am working hard to get these answer for the next SASWG meeting, on Thursday---I understand this is very important.

**Comment by lucabaldini** [comment]
I am attaching a presentation that is relevant to this
[lbaldini_grayfilter.pdf](https://github.com/lucabaldini/ixpeobssim/files/12696951/lbaldini_grayfilter.pdf)

**Comment by lucabaldini** [comment]
Also, I am closing the issue as, technically, I don't think this is a bug or a problem in the code, but we can continue discussing on this thread as new things come up.

**Comment by dovciak** [comment]
Thank you Luca! Michal.
-------- Pôvodná správa --------Od: Luca Baldini ***@***.***> Dátum: 22. 9. 2023  7:05  (GMT+01:00) Komu: lucabaldini/ixpeobssim ***@***.***> Kópia: dovciak ***@***.***>, Comment ***@***.***> Predmet: Re: [lucabaldini/ixpeobssim] PCUBE overestimation of polarization
  with gray filter below 3 KeV (Issue #714) 
I am attaching a presentation that is relevant to this
lbaldini_grayfilter.pdf
