### ISSUE TITLE
ixpeobssim uses 'angle_utilities' which has been deprecated in astropy 6.0

### ISSUE THREAD

**Issue by albertomanfreda** [lucabaldini/ixpeobssim#721]
Apparently in Astropy6.0  'angle_utilities', which is used in ixpeobssim.utils.astro to import 'angular_separation' is gone, and you should now import 'angular_separation' directly from 'astropy.coordinates'

https://docs.astropy.org/en/stable/changelog.html
https://github.com/cta-observatory/pyirf/issues/270

Thus ixpeobssim is currently not compatible with Astropy 6:

from ixpeobssim.utils import astro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/xpe/ixpeobssim/ixpeobssim/utils/astro.py", line 28, in <module>
    from astropy.coordinates import angle_utilities, SkyCoord
ImportError: cannot import name 'angle_utilities' from 'astropy.coordinates' (/home/alberto/heasoft/.heasoft-env/lib/python3.10/site-packages/astropy/coordinates/__init__.py)

**Comment by lucabaldini** [comment]
Looking into this...

**Comment by lucabaldini** [comment]
Shipped in 30.6.4
