### ISSUE TITLE
Significance calculation in kislat2015 needs to be fixed

### ISSUE THREAD

**Issue by steveehlert** [lucabaldini/ixpeobssim#727]
This is related to a previous update about the equivalent significance of a detection. 

On line 616 of evt/kislat2015.py the current code in the function calculate_stokes_errors  

` sig[mask] =  scipy.stats.norm.ppf(conf[mask])`

should change to 

`sig[mask] =  scipy.stats.norm.ppf(0.5 * conf[mask] + 0.5)`

such that it matches line 528 in the function significance

**Comment by lucabaldini** [comment]
Implementing the change...

**Comment by lucabaldini** [comment]
Fixed and shipped in 31.0.2
