### ISSUE TITLE
Issue: xpobssim.py Command Not Found After Reinstallation of ixpeobssim

### ISSUE THREAD

**Issue by IndraniPal93** [lucabaldini/ixpeobssim#730]
Here's how you can phrase the issue:

---

**Issue: xpobssim.py Command Not Found After Reinstallation of ixpeobssim**

Hi,

I installed `ixpeobssim` using the command `pip install ixpeobssim --user` and ran a simulation successfully. However, after uninstalling and reinstalling it using the same command, I now get an error when running the following command:

```
xpobssim.py --config ixpeobssim/config/toy_periodic_source.py --duration 1000
```

The error is:

```
bash: xpobssim.py: command not found
```

Any idea how to solve this issue?

Thanks!

**Comment by ndilalla** [comment]
Hi! Have you tried to run the app without the ".py" extension? Like:
`xpobssim --config ixpeobssim/config/toy_periodic_source.py --duration 1000`

**Comment by IndraniPal93** [comment]
Hi, yeah I tried and it worked. Sorry for my late reply. Thanks a lot for
your response to my query.

Best,
Indrani

**Comment by ndilalla** [comment]
Thank you for confirming. I will now close this issue.
